package com.flf.entity;

public class ShopCommoditySku {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_commodity_sku.sku_id
     *
     * @mbg.generated Wed Oct 18 16:44:01 CST 2017
     */
    private Integer skuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_commodity_sku.commodity_id
     *
     * @mbg.generated Wed Oct 18 16:44:01 CST 2017
     */
    private Integer commodityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_commodity_sku.sku_sale
     *
     * @mbg.generated Wed Oct 18 16:44:01 CST 2017
     */
    private String skuSale;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_commodity_sku.sku_rent
     *
     * @mbg.generated Wed Oct 18 16:44:01 CST 2017
     */
    private String skuRent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_commodity_sku.rent_stock
     *
     * @mbg.generated Wed Oct 18 16:44:01 CST 2017
     */
    private Integer rentStock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_commodity_sku.sale_stock
     *
     * @mbg.generated Wed Oct 18 16:44:01 CST 2017
     */
    private Integer saleStock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_commodity_sku.commoditySize
     *
     * @mbg.generated Wed Oct 18 16:44:01 CST 2017
     */
    private String commoditySize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_commodity_sku.color
     *
     * @mbg.generated Wed Oct 18 16:44:01 CST 2017
     */
    private String color;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_commodity_sku.img
     *
     * @mbg.generated Wed Oct 18 16:44:01 CST 2017
     */
    private String img;
    
    
    private Integer commodityHot;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_commodity_sku.sku_id
     *
     * @return the value of shop_commodity_sku.sku_id
     *
     * @mbg.generated Wed Oct 18 16:44:01 CST 2017
     */
    public Integer getSkuId() {
        return skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_commodity_sku.sku_id
     *
     * @param skuId the value for shop_commodity_sku.sku_id
     *
     * @mbg.generated Wed Oct 18 16:44:01 CST 2017
     */
    public void setSkuId(Integer skuId) {
        this.skuId = skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_commodity_sku.commodity_id
     *
     * @return the value of shop_commodity_sku.commodity_id
     *
     * @mbg.generated Wed Oct 18 16:44:01 CST 2017
     */
    public Integer getCommodityId() {
        return commodityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_commodity_sku.commodity_id
     *
     * @param commodityId the value for shop_commodity_sku.commodity_id
     *
     * @mbg.generated Wed Oct 18 16:44:01 CST 2017
     */
    public void setCommodityId(Integer commodityId) {
        this.commodityId = commodityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_commodity_sku.sku_sale
     *
     * @return the value of shop_commodity_sku.sku_sale
     *
     * @mbg.generated Wed Oct 18 16:44:01 CST 2017
     */
    public String getSkuSale() {
        return skuSale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_commodity_sku.sku_sale
     *
     * @param skuSale the value for shop_commodity_sku.sku_sale
     *
     * @mbg.generated Wed Oct 18 16:44:01 CST 2017
     */
    public void setSkuSale(String skuSale) {
        this.skuSale = skuSale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_commodity_sku.sku_rent
     *
     * @return the value of shop_commodity_sku.sku_rent
     *
     * @mbg.generated Wed Oct 18 16:44:01 CST 2017
     */
    public String getSkuRent() {
        return skuRent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_commodity_sku.sku_rent
     *
     * @param skuRent the value for shop_commodity_sku.sku_rent
     *
     * @mbg.generated Wed Oct 18 16:44:01 CST 2017
     */
    public void setSkuRent(String skuRent) {
        this.skuRent = skuRent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_commodity_sku.rent_stock
     *
     * @return the value of shop_commodity_sku.rent_stock
     *
     * @mbg.generated Wed Oct 18 16:44:01 CST 2017
     */
    public Integer getRentStock() {
        return rentStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_commodity_sku.rent_stock
     *
     * @param rentStock the value for shop_commodity_sku.rent_stock
     *
     * @mbg.generated Wed Oct 18 16:44:01 CST 2017
     */
    public void setRentStock(Integer rentStock) {
        this.rentStock = rentStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_commodity_sku.sale_stock
     *
     * @return the value of shop_commodity_sku.sale_stock
     *
     * @mbg.generated Wed Oct 18 16:44:01 CST 2017
     */
    public Integer getSaleStock() {
        return saleStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_commodity_sku.sale_stock
     *
     * @param saleStock the value for shop_commodity_sku.sale_stock
     *
     * @mbg.generated Wed Oct 18 16:44:01 CST 2017
     */
    public void setSaleStock(Integer saleStock) {
        this.saleStock = saleStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_commodity_sku.commoditySize
     *
     * @return the value of shop_commodity_sku.commoditySize
     *
     * @mbg.generated Wed Oct 18 16:44:01 CST 2017
     */
    public String getCommoditySize() {
        return commoditySize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_commodity_sku.commoditySize
     *
     * @param commoditysize the value for shop_commodity_sku.commoditySize
     *
     * @mbg.generated Wed Oct 18 16:44:01 CST 2017
     */
    public void setCommoditySize(String commoditySize) {
        this.commoditySize = commoditySize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_commodity_sku.color
     *
     * @return the value of shop_commodity_sku.color
     *
     * @mbg.generated Wed Oct 18 16:44:01 CST 2017
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_commodity_sku.color
     *
     * @param color the value for shop_commodity_sku.color
     *
     * @mbg.generated Wed Oct 18 16:44:01 CST 2017
     */
    public void setColor(String color) {
        this.color = color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_commodity_sku.img
     *
     * @return the value of shop_commodity_sku.img
     *
     * @mbg.generated Wed Oct 18 16:44:01 CST 2017
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_commodity_sku.img
     *
     * @param img the value for shop_commodity_sku.img
     *
     * @mbg.generated Wed Oct 18 16:44:01 CST 2017
     */
    public void setImg(String img) {
        this.img = img;
    }

	public Integer getCommodityHot() {
		return commodityHot;
	}

	public void setCommodityHot(Integer commodityHot) {
		this.commodityHot = commodityHot;
	}
}