package com.flf.entity;

import com.base.entity.BaseEntity;
/**
 * 
 * <br>
 * <b>功能：</b>ShopShouhouEntity<br>
 */
public class ShopShouhou extends BaseEntity {
	
		private java.lang.Integer id;//   	private java.lang.Integer userId;//   	private java.lang.Integer orderId;//   	private java.lang.Object type;//   1为退货换货 2为其他	private java.lang.String content;//   售后原因	private java.lang.String img;//   反馈图片	private java.lang.Integer createTime;//   申请时间	private java.lang.String orderCode;//   快递单号	private java.lang.String compNum;//   快递公司代码	private java.lang.String phone;//   申请人联系电话	private java.lang.String name;//   寄件人姓名	private java.lang.String address;//   寄件地址	private java.lang.Object status;//   资料填写	private java.lang.Object isDie;//   是否结束	public java.lang.Integer getId() {	    return this.id;	}	public void setId(java.lang.Integer id) {	    this.id=id;	}	public java.lang.Integer getUserId() {	    return this.userId;	}	public void setUserId(java.lang.Integer userId) {	    this.userId=userId;	}	public java.lang.Integer getOrderId() {	    return this.orderId;	}	public void setOrderId(java.lang.Integer orderId) {	    this.orderId=orderId;	}	public java.lang.Object getType() {	    return this.type;	}	public void setType(java.lang.Object type) {	    this.type=type;	}	public java.lang.String getContent() {	    return this.content;	}	public void setContent(java.lang.String content) {	    this.content=content;	}	public java.lang.String getImg() {	    return this.img;	}	public void setImg(java.lang.String img) {	    this.img=img;	}	public java.lang.Integer getCreateTime() {	    return this.createTime;	}	public void setCreateTime(java.lang.Integer createTime) {	    this.createTime=createTime;	}	public java.lang.String getOrderCode() {	    return this.orderCode;	}	public void setOrderCode(java.lang.String orderCode) {	    this.orderCode=orderCode;	}	public java.lang.String getCompNum() {	    return this.compNum;	}	public void setCompNum(java.lang.String compNum) {	    this.compNum=compNum;	}	public java.lang.String getPhone() {	    return this.phone;	}	public void setPhone(java.lang.String phone) {	    this.phone=phone;	}	public java.lang.String getName() {	    return this.name;	}	public void setName(java.lang.String name) {	    this.name=name;	}	public java.lang.String getAddress() {	    return this.address;	}	public void setAddress(java.lang.String address) {	    this.address=address;	}	public java.lang.Object getStatus() {	    return this.status;	}	public void setStatus(java.lang.Object status) {	    this.status=status;	}	public java.lang.Object getIsDie() {	    return this.isDie;	}	public void setIsDie(java.lang.Object isDie) {	    this.isDie=isDie;	}
}

