package com.flf.entity;

import java.util.ArrayList;
import java.util.List;

public class ShopCommoditySkuExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shop_commodity_sku
     *
     * @mbg.generated Wed Oct 18 16:44:01 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shop_commodity_sku
     *
     * @mbg.generated Wed Oct 18 16:44:01 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shop_commodity_sku
     *
     * @mbg.generated Wed Oct 18 16:44:01 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_commodity_sku
     *
     * @mbg.generated Wed Oct 18 16:44:01 CST 2017
     */
    public ShopCommoditySkuExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_commodity_sku
     *
     * @mbg.generated Wed Oct 18 16:44:01 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_commodity_sku
     *
     * @mbg.generated Wed Oct 18 16:44:01 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_commodity_sku
     *
     * @mbg.generated Wed Oct 18 16:44:01 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_commodity_sku
     *
     * @mbg.generated Wed Oct 18 16:44:01 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_commodity_sku
     *
     * @mbg.generated Wed Oct 18 16:44:01 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_commodity_sku
     *
     * @mbg.generated Wed Oct 18 16:44:01 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_commodity_sku
     *
     * @mbg.generated Wed Oct 18 16:44:01 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_commodity_sku
     *
     * @mbg.generated Wed Oct 18 16:44:01 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_commodity_sku
     *
     * @mbg.generated Wed Oct 18 16:44:01 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_commodity_sku
     *
     * @mbg.generated Wed Oct 18 16:44:01 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table shop_commodity_sku
     *
     * @mbg.generated Wed Oct 18 16:44:01 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSkuIdIsNull() {
            addCriterion("sku_id is null");
            return (Criteria) this;
        }

        public Criteria andSkuIdIsNotNull() {
            addCriterion("sku_id is not null");
            return (Criteria) this;
        }

        public Criteria andSkuIdEqualTo(Integer value) {
            addCriterion("sku_id =", value, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdNotEqualTo(Integer value) {
            addCriterion("sku_id <>", value, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdGreaterThan(Integer value) {
            addCriterion("sku_id >", value, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("sku_id >=", value, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdLessThan(Integer value) {
            addCriterion("sku_id <", value, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdLessThanOrEqualTo(Integer value) {
            addCriterion("sku_id <=", value, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdIn(List<Integer> values) {
            addCriterion("sku_id in", values, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdNotIn(List<Integer> values) {
            addCriterion("sku_id not in", values, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdBetween(Integer value1, Integer value2) {
            addCriterion("sku_id between", value1, value2, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdNotBetween(Integer value1, Integer value2) {
            addCriterion("sku_id not between", value1, value2, "skuId");
            return (Criteria) this;
        }

        public Criteria andCommodityIdIsNull() {
            addCriterion("commodity_id is null");
            return (Criteria) this;
        }

        public Criteria andCommodityIdIsNotNull() {
            addCriterion("commodity_id is not null");
            return (Criteria) this;
        }

        public Criteria andCommodityIdEqualTo(Integer value) {
            addCriterion("commodity_id =", value, "commodityId");
            return (Criteria) this;
        }

        public Criteria andCommodityIdNotEqualTo(Integer value) {
            addCriterion("commodity_id <>", value, "commodityId");
            return (Criteria) this;
        }

        public Criteria andCommodityIdGreaterThan(Integer value) {
            addCriterion("commodity_id >", value, "commodityId");
            return (Criteria) this;
        }

        public Criteria andCommodityIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("commodity_id >=", value, "commodityId");
            return (Criteria) this;
        }

        public Criteria andCommodityIdLessThan(Integer value) {
            addCriterion("commodity_id <", value, "commodityId");
            return (Criteria) this;
        }

        public Criteria andCommodityIdLessThanOrEqualTo(Integer value) {
            addCriterion("commodity_id <=", value, "commodityId");
            return (Criteria) this;
        }

        public Criteria andCommodityIdIn(List<Integer> values) {
            addCriterion("commodity_id in", values, "commodityId");
            return (Criteria) this;
        }

        public Criteria andCommodityIdNotIn(List<Integer> values) {
            addCriterion("commodity_id not in", values, "commodityId");
            return (Criteria) this;
        }

        public Criteria andCommodityIdBetween(Integer value1, Integer value2) {
            addCriterion("commodity_id between", value1, value2, "commodityId");
            return (Criteria) this;
        }

        public Criteria andCommodityIdNotBetween(Integer value1, Integer value2) {
            addCriterion("commodity_id not between", value1, value2, "commodityId");
            return (Criteria) this;
        }

        public Criteria andSkuSaleIsNull() {
            addCriterion("sku_sale is null");
            return (Criteria) this;
        }

        public Criteria andSkuSaleIsNotNull() {
            addCriterion("sku_sale is not null");
            return (Criteria) this;
        }

        public Criteria andSkuSaleEqualTo(String value) {
            addCriterion("sku_sale =", value, "skuSale");
            return (Criteria) this;
        }

        public Criteria andSkuSaleNotEqualTo(String value) {
            addCriterion("sku_sale <>", value, "skuSale");
            return (Criteria) this;
        }

        public Criteria andSkuSaleGreaterThan(String value) {
            addCriterion("sku_sale >", value, "skuSale");
            return (Criteria) this;
        }

        public Criteria andSkuSaleGreaterThanOrEqualTo(String value) {
            addCriterion("sku_sale >=", value, "skuSale");
            return (Criteria) this;
        }

        public Criteria andSkuSaleLessThan(String value) {
            addCriterion("sku_sale <", value, "skuSale");
            return (Criteria) this;
        }

        public Criteria andSkuSaleLessThanOrEqualTo(String value) {
            addCriterion("sku_sale <=", value, "skuSale");
            return (Criteria) this;
        }

        public Criteria andSkuSaleLike(String value) {
            addCriterion("sku_sale like", value, "skuSale");
            return (Criteria) this;
        }

        public Criteria andSkuSaleNotLike(String value) {
            addCriterion("sku_sale not like", value, "skuSale");
            return (Criteria) this;
        }

        public Criteria andSkuSaleIn(List<String> values) {
            addCriterion("sku_sale in", values, "skuSale");
            return (Criteria) this;
        }

        public Criteria andSkuSaleNotIn(List<String> values) {
            addCriterion("sku_sale not in", values, "skuSale");
            return (Criteria) this;
        }

        public Criteria andSkuSaleBetween(String value1, String value2) {
            addCriterion("sku_sale between", value1, value2, "skuSale");
            return (Criteria) this;
        }

        public Criteria andSkuSaleNotBetween(String value1, String value2) {
            addCriterion("sku_sale not between", value1, value2, "skuSale");
            return (Criteria) this;
        }

        public Criteria andSkuRentIsNull() {
            addCriterion("sku_rent is null");
            return (Criteria) this;
        }

        public Criteria andSkuRentIsNotNull() {
            addCriterion("sku_rent is not null");
            return (Criteria) this;
        }

        public Criteria andSkuRentEqualTo(String value) {
            addCriterion("sku_rent =", value, "skuRent");
            return (Criteria) this;
        }

        public Criteria andSkuRentNotEqualTo(String value) {
            addCriterion("sku_rent <>", value, "skuRent");
            return (Criteria) this;
        }

        public Criteria andSkuRentGreaterThan(String value) {
            addCriterion("sku_rent >", value, "skuRent");
            return (Criteria) this;
        }

        public Criteria andSkuRentGreaterThanOrEqualTo(String value) {
            addCriterion("sku_rent >=", value, "skuRent");
            return (Criteria) this;
        }

        public Criteria andSkuRentLessThan(String value) {
            addCriterion("sku_rent <", value, "skuRent");
            return (Criteria) this;
        }

        public Criteria andSkuRentLessThanOrEqualTo(String value) {
            addCriterion("sku_rent <=", value, "skuRent");
            return (Criteria) this;
        }

        public Criteria andSkuRentLike(String value) {
            addCriterion("sku_rent like", value, "skuRent");
            return (Criteria) this;
        }

        public Criteria andSkuRentNotLike(String value) {
            addCriterion("sku_rent not like", value, "skuRent");
            return (Criteria) this;
        }

        public Criteria andSkuRentIn(List<String> values) {
            addCriterion("sku_rent in", values, "skuRent");
            return (Criteria) this;
        }

        public Criteria andSkuRentNotIn(List<String> values) {
            addCriterion("sku_rent not in", values, "skuRent");
            return (Criteria) this;
        }

        public Criteria andSkuRentBetween(String value1, String value2) {
            addCriterion("sku_rent between", value1, value2, "skuRent");
            return (Criteria) this;
        }

        public Criteria andSkuRentNotBetween(String value1, String value2) {
            addCriterion("sku_rent not between", value1, value2, "skuRent");
            return (Criteria) this;
        }

        public Criteria andRentStockIsNull() {
            addCriterion("rent_stock is null");
            return (Criteria) this;
        }

        public Criteria andRentStockIsNotNull() {
            addCriterion("rent_stock is not null");
            return (Criteria) this;
        }

        public Criteria andRentStockEqualTo(Integer value) {
            addCriterion("rent_stock =", value, "rentStock");
            return (Criteria) this;
        }

        public Criteria andRentStockNotEqualTo(Integer value) {
            addCriterion("rent_stock <>", value, "rentStock");
            return (Criteria) this;
        }

        public Criteria andRentStockGreaterThan(Integer value) {
            addCriterion("rent_stock >", value, "rentStock");
            return (Criteria) this;
        }

        public Criteria andRentStockGreaterThanOrEqualTo(Integer value) {
            addCriterion("rent_stock >=", value, "rentStock");
            return (Criteria) this;
        }

        public Criteria andRentStockLessThan(Integer value) {
            addCriterion("rent_stock <", value, "rentStock");
            return (Criteria) this;
        }

        public Criteria andRentStockLessThanOrEqualTo(Integer value) {
            addCriterion("rent_stock <=", value, "rentStock");
            return (Criteria) this;
        }

        public Criteria andRentStockIn(List<Integer> values) {
            addCriterion("rent_stock in", values, "rentStock");
            return (Criteria) this;
        }

        public Criteria andRentStockNotIn(List<Integer> values) {
            addCriterion("rent_stock not in", values, "rentStock");
            return (Criteria) this;
        }

        public Criteria andRentStockBetween(Integer value1, Integer value2) {
            addCriterion("rent_stock between", value1, value2, "rentStock");
            return (Criteria) this;
        }

        public Criteria andRentStockNotBetween(Integer value1, Integer value2) {
            addCriterion("rent_stock not between", value1, value2, "rentStock");
            return (Criteria) this;
        }

        public Criteria andSaleStockIsNull() {
            addCriterion("sale_stock is null");
            return (Criteria) this;
        }

        public Criteria andSaleStockIsNotNull() {
            addCriterion("sale_stock is not null");
            return (Criteria) this;
        }

        public Criteria andSaleStockEqualTo(Integer value) {
            addCriterion("sale_stock =", value, "saleStock");
            return (Criteria) this;
        }

        public Criteria andSaleStockNotEqualTo(Integer value) {
            addCriterion("sale_stock <>", value, "saleStock");
            return (Criteria) this;
        }

        public Criteria andSaleStockGreaterThan(Integer value) {
            addCriterion("sale_stock >", value, "saleStock");
            return (Criteria) this;
        }

        public Criteria andSaleStockGreaterThanOrEqualTo(Integer value) {
            addCriterion("sale_stock >=", value, "saleStock");
            return (Criteria) this;
        }

        public Criteria andSaleStockLessThan(Integer value) {
            addCriterion("sale_stock <", value, "saleStock");
            return (Criteria) this;
        }

        public Criteria andSaleStockLessThanOrEqualTo(Integer value) {
            addCriterion("sale_stock <=", value, "saleStock");
            return (Criteria) this;
        }

        public Criteria andSaleStockIn(List<Integer> values) {
            addCriterion("sale_stock in", values, "saleStock");
            return (Criteria) this;
        }

        public Criteria andSaleStockNotIn(List<Integer> values) {
            addCriterion("sale_stock not in", values, "saleStock");
            return (Criteria) this;
        }

        public Criteria andSaleStockBetween(Integer value1, Integer value2) {
            addCriterion("sale_stock between", value1, value2, "saleStock");
            return (Criteria) this;
        }

        public Criteria andSaleStockNotBetween(Integer value1, Integer value2) {
            addCriterion("sale_stock not between", value1, value2, "saleStock");
            return (Criteria) this;
        }

        public Criteria andCommoditysizeIsNull() {
            addCriterion("commoditySize is null");
            return (Criteria) this;
        }

        public Criteria andCommoditysizeIsNotNull() {
            addCriterion("commoditySize is not null");
            return (Criteria) this;
        }

        public Criteria andCommoditysizeEqualTo(String value) {
            addCriterion("commoditySize =", value, "commoditysize");
            return (Criteria) this;
        }

        public Criteria andCommoditysizeNotEqualTo(String value) {
            addCriterion("commoditySize <>", value, "commoditysize");
            return (Criteria) this;
        }

        public Criteria andCommoditysizeGreaterThan(String value) {
            addCriterion("commoditySize >", value, "commoditysize");
            return (Criteria) this;
        }

        public Criteria andCommoditysizeGreaterThanOrEqualTo(String value) {
            addCriterion("commoditySize >=", value, "commoditysize");
            return (Criteria) this;
        }

        public Criteria andCommoditysizeLessThan(String value) {
            addCriterion("commoditySize <", value, "commoditysize");
            return (Criteria) this;
        }

        public Criteria andCommoditysizeLessThanOrEqualTo(String value) {
            addCriterion("commoditySize <=", value, "commoditysize");
            return (Criteria) this;
        }

        public Criteria andCommoditysizeLike(String value) {
            addCriterion("commoditySize like", value, "commoditysize");
            return (Criteria) this;
        }

        public Criteria andCommoditysizeNotLike(String value) {
            addCriterion("commoditySize not like", value, "commoditysize");
            return (Criteria) this;
        }

        public Criteria andCommoditysizeIn(List<String> values) {
            addCriterion("commoditySize in", values, "commoditysize");
            return (Criteria) this;
        }

        public Criteria andCommoditysizeNotIn(List<String> values) {
            addCriterion("commoditySize not in", values, "commoditysize");
            return (Criteria) this;
        }

        public Criteria andCommoditysizeBetween(String value1, String value2) {
            addCriterion("commoditySize between", value1, value2, "commoditysize");
            return (Criteria) this;
        }

        public Criteria andCommoditysizeNotBetween(String value1, String value2) {
            addCriterion("commoditySize not between", value1, value2, "commoditysize");
            return (Criteria) this;
        }

        public Criteria andColorIsNull() {
            addCriterion("color is null");
            return (Criteria) this;
        }

        public Criteria andColorIsNotNull() {
            addCriterion("color is not null");
            return (Criteria) this;
        }

        public Criteria andColorEqualTo(String value) {
            addCriterion("color =", value, "color");
            return (Criteria) this;
        }

        public Criteria andColorNotEqualTo(String value) {
            addCriterion("color <>", value, "color");
            return (Criteria) this;
        }

        public Criteria andColorGreaterThan(String value) {
            addCriterion("color >", value, "color");
            return (Criteria) this;
        }

        public Criteria andColorGreaterThanOrEqualTo(String value) {
            addCriterion("color >=", value, "color");
            return (Criteria) this;
        }

        public Criteria andColorLessThan(String value) {
            addCriterion("color <", value, "color");
            return (Criteria) this;
        }

        public Criteria andColorLessThanOrEqualTo(String value) {
            addCriterion("color <=", value, "color");
            return (Criteria) this;
        }

        public Criteria andColorLike(String value) {
            addCriterion("color like", value, "color");
            return (Criteria) this;
        }

        public Criteria andColorNotLike(String value) {
            addCriterion("color not like", value, "color");
            return (Criteria) this;
        }

        public Criteria andColorIn(List<String> values) {
            addCriterion("color in", values, "color");
            return (Criteria) this;
        }

        public Criteria andColorNotIn(List<String> values) {
            addCriterion("color not in", values, "color");
            return (Criteria) this;
        }

        public Criteria andColorBetween(String value1, String value2) {
            addCriterion("color between", value1, value2, "color");
            return (Criteria) this;
        }

        public Criteria andColorNotBetween(String value1, String value2) {
            addCriterion("color not between", value1, value2, "color");
            return (Criteria) this;
        }

        public Criteria andImgIsNull() {
            addCriterion("img is null");
            return (Criteria) this;
        }

        public Criteria andImgIsNotNull() {
            addCriterion("img is not null");
            return (Criteria) this;
        }

        public Criteria andImgEqualTo(String value) {
            addCriterion("img =", value, "img");
            return (Criteria) this;
        }

        public Criteria andImgNotEqualTo(String value) {
            addCriterion("img <>", value, "img");
            return (Criteria) this;
        }

        public Criteria andImgGreaterThan(String value) {
            addCriterion("img >", value, "img");
            return (Criteria) this;
        }

        public Criteria andImgGreaterThanOrEqualTo(String value) {
            addCriterion("img >=", value, "img");
            return (Criteria) this;
        }

        public Criteria andImgLessThan(String value) {
            addCriterion("img <", value, "img");
            return (Criteria) this;
        }

        public Criteria andImgLessThanOrEqualTo(String value) {
            addCriterion("img <=", value, "img");
            return (Criteria) this;
        }

        public Criteria andImgLike(String value) {
            addCriterion("img like", value, "img");
            return (Criteria) this;
        }

        public Criteria andImgNotLike(String value) {
            addCriterion("img not like", value, "img");
            return (Criteria) this;
        }

        public Criteria andImgIn(List<String> values) {
            addCriterion("img in", values, "img");
            return (Criteria) this;
        }

        public Criteria andImgNotIn(List<String> values) {
            addCriterion("img not in", values, "img");
            return (Criteria) this;
        }

        public Criteria andImgBetween(String value1, String value2) {
            addCriterion("img between", value1, value2, "img");
            return (Criteria) this;
        }

        public Criteria andImgNotBetween(String value1, String value2) {
            addCriterion("img not between", value1, value2, "img");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table shop_commodity_sku
     *
     * @mbg.generated do_not_delete_during_merge Wed Oct 18 16:44:01 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table shop_commodity_sku
     *
     * @mbg.generated Wed Oct 18 16:44:01 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}