package com.flf.mapper;

import com.base.dao.BaseDao;
import com.flf.entity.ShopCommoditySku;
import com.flf.entity.ShopCommoditySkuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShopCommoditySkuMapper extends BaseDao{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_commodity_sku
     *
     * @mbg.generated Wed Oct 18 16:44:01 CST 2017
     */
    long countByExample(ShopCommoditySkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_commodity_sku
     *
     * @mbg.generated Wed Oct 18 16:44:01 CST 2017
     */
    int deleteByExample(ShopCommoditySkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_commodity_sku
     *
     * @mbg.generated Wed Oct 18 16:44:01 CST 2017
     */
    int deleteByPrimaryKey(Integer skuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_commodity_sku
     *
     * @mbg.generated Wed Oct 18 16:44:01 CST 2017
     */
    int insert(ShopCommoditySku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_commodity_sku
     *
     * @mbg.generated Wed Oct 18 16:44:01 CST 2017
     */
    int insertSelective(ShopCommoditySku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_commodity_sku
     *
     * @mbg.generated Wed Oct 18 16:44:01 CST 2017
     */
    List<ShopCommoditySku> selectByExample(ShopCommoditySkuExample example);
    
    List<ShopCommoditySku> list(Integer commodityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_commodity_sku
     *
     * @mbg.generated Wed Oct 18 16:44:01 CST 2017
     */
    ShopCommoditySku selectByPrimaryKey(Integer skuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_commodity_sku
     *
     * @mbg.generated Wed Oct 18 16:44:01 CST 2017
     */
    int updateByExampleSelective(@Param("record") ShopCommoditySku record, @Param("example") ShopCommoditySkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_commodity_sku
     *
     * @mbg.generated Wed Oct 18 16:44:01 CST 2017
     */
    int updateByExample(@Param("record") ShopCommoditySku record, @Param("example") ShopCommoditySkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_commodity_sku
     *
     * @mbg.generated Wed Oct 18 16:44:01 CST 2017
     */
    int updateByPrimaryKeySelective(ShopCommoditySku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_commodity_sku
     *
     * @mbg.generated Wed Oct 18 16:44:01 CST 2017
     */
    int updateByPrimaryKey(ShopCommoditySku record);
}