package com.flf.entity;

import com.base.entity.BaseEntity;
/**
 * 
 * <br>
 * <b>功能：</b>ShopMemberEntity<br>
 */
public class ShopMember extends BaseEntity {
	
		private java.lang.Integer memberId;//   会员ID	private java.lang.Integer memberLevel;//   会员等级	private java.lang.Float memberIntegral;//   会员积分	private java.lang.String memberTel;//   会员电话	private java.lang.String memberEmail;//   会员邮箱	private java.lang.Object memberSex;//   会员性别	private java.lang.String memberAddress;//   会员居住地址	private java.lang.String memberProfession;//   会员职业	private java.lang.String memberHobby;//   会员爱好	private java.lang.Integer buyTime;//   购买会员时间	private java.lang.Integer createTime;//   创建时间	private java.lang.String memberOpenid;//   用户关注获取的openID	private java.lang.Integer userId;//   会员对应的用户ID	public java.lang.Integer getMemberId() {	    return this.memberId;	}	public void setMemberId(java.lang.Integer memberId) {	    this.memberId=memberId;	}	public java.lang.Integer getMemberLevel() {	    return this.memberLevel;	}	public void setMemberLevel(java.lang.Integer memberLevel) {	    this.memberLevel=memberLevel;	}	public java.lang.Float getMemberIntegral() {	    return this.memberIntegral;	}	public void setMemberIntegral(java.lang.Float memberIntegral) {	    this.memberIntegral=memberIntegral;	}	public java.lang.String getMemberTel() {	    return this.memberTel;	}	public void setMemberTel(java.lang.String memberTel) {	    this.memberTel=memberTel;	}	public java.lang.String getMemberEmail() {	    return this.memberEmail;	}	public void setMemberEmail(java.lang.String memberEmail) {	    this.memberEmail=memberEmail;	}	public java.lang.Object getMemberSex() {	    return this.memberSex;	}	public void setMemberSex(java.lang.Object memberSex) {	    this.memberSex=memberSex;	}	public java.lang.String getMemberAddress() {	    return this.memberAddress;	}	public void setMemberAddress(java.lang.String memberAddress) {	    this.memberAddress=memberAddress;	}	public java.lang.String getMemberProfession() {	    return this.memberProfession;	}	public void setMemberProfession(java.lang.String memberProfession) {	    this.memberProfession=memberProfession;	}	public java.lang.String getMemberHobby() {	    return this.memberHobby;	}	public void setMemberHobby(java.lang.String memberHobby) {	    this.memberHobby=memberHobby;	}	public java.lang.Integer getBuyTime() {	    return this.buyTime;	}	public void setBuyTime(java.lang.Integer buyTime) {	    this.buyTime=buyTime;	}	public java.lang.Integer getCreateTime() {	    return this.createTime;	}	public void setCreateTime(java.lang.Integer createTime) {	    this.createTime=createTime;	}	public java.lang.String getMemberOpenid() {	    return this.memberOpenid;	}	public void setMemberOpenid(java.lang.String memberOpenid) {	    this.memberOpenid=memberOpenid;	}	public java.lang.Integer getUserId() {	    return this.userId;	}	public void setUserId(java.lang.Integer userId) {	    this.userId=userId;	}
}

